CREATE CATALOG IF NOT EXISTS cse587;
CREATE SCHEMA IF NOT EXISTS cse587.cve_assignment;
CREATE VOLUME IF NOT EXISTS cse587.cve_assignment.cve_data;
CREATE DATABASE IF NOT EXISTS cse587.bronze;
CREATE DATABASE IF NOT EXISTS cse587.silver;
CREATE DATABASE IF NOT EXISTS cse587.gold;

SHOW CATALOGS;